services:
  - type: web
    name: lncarrental-app
    env: docker
    buildCommand: "docker build -t lncarrental-app ."
    startCommand: "docker run -p 8080:80 lncarrental-app"
    envVars:
      - key: FLUTTER_WEB_HOST
        value: "0.0.0.0"